---
title: "Simulations semantic interference"
author: "Audrey Buerki & Pam Fuhrmeister"
date: "8 June 2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse) # for data wrangling, pipes, and good dataviz
library(lmerTest)  # for mixed effect models
library(ggthemes)
knitr::opts_chunk$set(echo = TRUE)
theme_set(theme_few(base_size = 10))
options("scipen"=10, "digits"=4) # control scientific notation
```

```{r include=FALSE}
# rexgauss function from retimes package
# package is no longer available on cran, so we create the function here
rexgauss <- function(n, mu=0, sigma=1, tau=1, positive=TRUE) {
    if(positive) {
        while(1) {
            x <- rnorm(n,mu,sigma)+rexp(n,1/tau)
            if(sum(x>0)==n) break
        }
    } else
        x <- rnorm(n,mu,sigma)+rexp(n,1/tau)
    return(x)
}

```

## Simulate data from an ex-gaussian distribution
```{r warning=FALSE, message=FALSE}
set.seed(8675309)
# exgaussian parameters that are estimated from data sets from meta analysis
rel_mu <- 578
rel_sigma <- 68
rel_tau <- 219
unr_mu <- 570
unr_sigma <- 53
unr_tau <- 202

id = rep(1:100, each = 100) # make a vector of participants 
item = rep(1:50, each = 2, length.out = length(id))
condition = rep(c("related", "unrelated"), times = length(id)/2)

dat <- data.frame(id,item,condition)

per_participant_intercept = rnorm(100, mean = 0, sd = 100)
per_item_intercept = rnorm(50, mean = 0, sd = 70) # sd estimated from pilot data
participant <- data.frame(id = rep(1:100), per_participant_intercept)
ggplot(participant, aes(per_participant_intercept)) +
  geom_density()
items <- data.frame(item = rep(1:50), per_item_intercept)
ggplot(items, aes(per_item_intercept)) +
  geom_density()

dat <- merge(dat, participant, by = "id")
dat <- merge(dat, items, by = "item")

dat$err <- rnorm(n = length(dat), mean = 0, sd = 100)

dat$response <- ifelse(dat$condition == "related", rexgauss(length(id), mu = rel_mu + dat$per_participant_intercept + dat$per_item_intercept + dat$err, sigma = rel_sigma, tau = rel_tau), rexgauss(length(id), mu = unr_mu + dat$per_participant_intercept + dat$per_item_intercept + dat$err, sigma = unr_sigma, tau = unr_tau))

```


## Look at data

```{r warning=FALSE, message=FALSE}
# plot distributions of data by condition (related/unrelated)
ggplot(dat, aes(response, fill = condition)) +
  geom_density(alpha = .5)

dat$condition <- as.factor(dat$condition)
contrasts(dat$condition) <- c(.5,-.5)

m0 <- lmer(response ~ condition + (1|id) + (1|item), data = dat) 
mat_trt <- model.matrix(m0)
dat$cont.cond <- mat_trt[,2] 
# fit model with simulated data
summary(mod <- lmer(log(response) ~ cont.cond + 
                      (cont.cond || id) +
                      (cont.cond || item),
                    data = dat))

summary(mod1 <- lmer(response ~ cont.cond + 
                      (cont.cond || id) +
                      (cont.cond || item),
                    data = dat))

```

## Compute quantiles

```{r warning=FALSE, message=FALSE}

# calculate delta plot slopes and mean interference effects from simulated data
quantiles <- dat %>%
  group_by(id, condition) %>%
  mutate(quantile = cut(response, breaks = quantile(response, probs = seq(0,1,.2), type = 7),
                        include.lowest = TRUE, labels = 1:5)) %>%
  group_by(id, condition, quantile) %>%
  #ungroup()%>%
  #group_by(quantile) %>%
  summarize(mean_quantile = mean(response)) 


quantiles_item <- dat %>%
  group_by(item, condition) %>%
  mutate(quantile = cut(response, breaks = quantile(response, probs = seq(0,1,.2), type = 7),
                        include.lowest = TRUE, labels = 1:5)) %>%
  group_by(item, condition, quantile) %>%
    #ungroup() %>%
    #group_by(quantile) %>%
    summarize(mean_quantile_items = mean(response))

quantiles_wide <- quantiles %>%
  pivot_wider(names_from = c(condition, quantile), values_from = mean_quantile)

quantiles_wide_item <- quantiles_item %>%
  pivot_wider(names_from = c(condition, quantile), values_from = mean_quantile_items)

quantiles_plot_data <- quantiles %>%
  group_by(condition, quantile) %>%
  summarize(mean_RT = mean(mean_quantile))

quantiles_plot_data_items <- quantiles_item %>%
  group_by(condition, quantile) %>%
  summarize(mean_RT = mean(mean_quantile_items))

quantiles_plot_data$condition <- as.factor(as.character(quantiles_plot_data$condition))
plot_pp <-ggplot(quantiles_plot_data, aes(x = mean_RT, y = quantile, color = condition, group = condition)) +
  geom_point(stat = "identity") +
  geom_line() +
  scale_color_viridis_d("condition")
plot_pp

quantiles_plot_data_items$condition <- as.factor(as.character(quantiles_plot_data_items$condition))

plot_item <-ggplot(quantiles_plot_data_items, aes(x = mean_RT, y = quantile, color = condition, group = condition)) +
  geom_point(stat = "identity") +
  geom_line() +
  scale_color_viridis_d("condition")
plot_item
```

# Compute slopes

```{r warning=FALSE, message=FALSE}
slope_2_1 <- quantiles_wide %>%
  mutate(delta_2 = related_2 - unrelated_2) %>%
  mutate(delta_1 = related_1 - unrelated_1) %>%
  mutate(mean_2 = ((related_2 + unrelated_2)/2)) %>%
  mutate(mean_1 = ((related_1 + unrelated_1)/2)) %>%
  group_by(id) %>%
  summarize(slope_2_1 = (delta_2 - delta_1)/(mean_2 - mean_1))

slope_2_1_item <- quantiles_wide_item %>%
  mutate(delta_2 = related_2 - unrelated_2) %>%
  mutate(delta_1 = related_1 - unrelated_1) %>%
  mutate(mean_2 = ((related_2 + unrelated_2)/2)) %>%
  mutate(mean_1 = ((related_1 + unrelated_1)/2)) %>%
  group_by(item) %>%
  summarize(slope_2_1_item = (delta_2 - delta_1)/(mean_2 - mean_1))

slope_5_4 <- quantiles_wide %>%  
  mutate(delta_5 = related_5 - unrelated_5) %>%
  mutate(delta_4 = related_4 - unrelated_4) %>%
  mutate(mean_5 = ((related_5 + unrelated_5)/2)) %>%
  mutate(mean_4 = ((related_4 + unrelated_4)/2)) %>%
  group_by(id) %>%
  summarize(slope_5_4 = (delta_5 - delta_4)/(mean_5 - mean_4))

slope_5_4_item <- quantiles_wide_item %>%
  mutate(delta_5 = related_5 - unrelated_5) %>%
  mutate(delta_4 = related_4 - unrelated_4) %>%
  mutate(mean_5 = ((related_5 + unrelated_5)/2)) %>%
  mutate(mean_4 = ((related_4 + unrelated_4)/2)) %>%
  group_by(item) %>%
  summarize(slope_5_4_item = (delta_5 - delta_4)/(mean_5 - mean_4))
```


# Correlations


```{r warning=FALSE, message=FALSE}
sem_int <- dat %>%
  group_by(id, condition) %>%
  summarize(mean_cond = mean(response)) %>%
  pivot_wider(names_from = condition, values_from = mean_cond) %>%
  mutate(sem_int = related - unrelated)

# semantic interference effect by item
sem_int_item <- dat %>%
  group_by(item,condition) %>%
  summarize(mean_cond = mean(response)) %>%
  pivot_wider(names_from = condition, values_from = mean_cond) %>%
  mutate(sem_int_item = related - unrelated)

cor_participants <- merge(sem_int, slope_5_4, by = "id")
cor_participants <- merge(cor_participants, slope_2_1, by = "id")
cor_items <- merge(sem_int_item, slope_5_4_item, by = "item")
cor_items <- merge(cor_items, slope_2_1_item, by = "item")

cor.test(cor_participants$slope_5_4, cor_participants$sem_int)
cor.test(cor_participants$slope_2_1, cor_participants$sem_int)
cor.test(cor_items$slope_5_4_item, cor_items$sem_int_item)
cor.test(cor_items$slope_2_1_item, cor_items$sem_int_item)

```

# Add plot of effect size as a function of segment
```{r warning=FALSE, message=FALSE}

fast_slope_pp <-left_join(sem_int, slope_2_1, by = NULL, copy = FALSE)

plot_fast_pp <-ggplot(fast_slope_pp, aes(x = sem_int, y = slope_2_1)) +
  geom_point(stat = "identity") +
  geom_smooth(method = "lm", color = "darkgray") +
  labs(title = "Participants: fast delta segment", x = "Mean semantic interference effect", y = "Slope of fastest delta segment")
plot_fast_pp


fast_slope_item <-left_join(sem_int_item, slope_2_1_item, by = NULL, copy = FALSE)

plot_fast_item <-ggplot(fast_slope_item, aes(x = sem_int_item, y = slope_2_1_item)) +
  geom_point(stat = "identity") +
  geom_smooth(method = "lm", color = "darkgray") +
  labs(title = "Items: fast delta segment", x = "Mean semantic interference effect", y = "Slope of fastest delta segment")
plot_fast_item



slow_slope_pp <-left_join(sem_int, slope_5_4, by = NULL, copy = FALSE)

plot_slow_pp <-ggplot(slow_slope_pp, aes(x = sem_int, y = slope_5_4)) +
  geom_point(stat = "identity") +
  geom_smooth(method = "lm", color = "darkgray") +
  labs(title = "Participants: slow delta segment", x = "Mean semantic interference effect", y = "Slope of slowest delta segment")
plot_slow_pp


slow_slope_item <-left_join(sem_int_item, slope_5_4_item, by = NULL, copy = FALSE)

plot_slow_item <-ggplot(slow_slope_item, aes(x = sem_int_item, y = slope_5_4_item)) +
  geom_point(stat = "identity") +
  geom_smooth(method = "lm", color = "darkgray") +
  labs(title = "Items: slow delta segment", x = "Mean semantic interference effect", y = "Slope of slowest delta segment")
plot_slow_item


figure <- cowplot::plot_grid(plot_slow_pp, plot_fast_pp, plot_slow_item, plot_fast_item, ncol = 2, labels = c("A","B","C","D"))
figure

```

